# -*- coding: utf-8 -*-
"""taller numerico2-p6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/richfon/Analisis_Numerico/blob/main/Talleres/Taller2/taller_numerico2_p6.ipynb
"""

import numpy as np
import pandas as pd

def jacobi(A, b, tol, its, x0):
    iters = []
    xs = []
    x = x0
    i=1
    while i < its:
        xs.append(x)
        iters.append(i)
        inv = np.linalg.inv(D)
        x0 = x
        x = np.dot(inv, b)-np.dot(inv, (np.dot(LU, x)))
        i=i+1
        if np.linalg.norm(x - x0) < tol:
            return x, i, iters, xs
    return x, i, iters, xs
        
def gaussSeidel(A, b, tol, its, x0):   
    iteraciones = 1
    x = x0
    n = 3
    m = 3
    dif = np.ones(n, dtype = float)
    err = 2*tol
    k=0
    while k < its:
        k=k+1
        for i in range (m):
            suma = 0
            for j in range (n):
                    if j != i:
                        suma = suma + A[i][j]*x[j]
            x1 = (b[i] - suma)/A[i][i]
            dif[i] = abs(x1 - x[i])
            x[i] = x1
        err = np.max(dif)
        iters.append(iteraciones)
        iteraciones += 1
        if err < tol:
            return x, iteraciones
    return x, iteraciones


#Se definen Alfa y Beta de tal forma que cumpla con que la matriz es diagonalmente dominante, de tal forma que converga.
#cualquier valor es viable excepto la excepcion indicada
#Esto porque 
#x=(1-0y+z)/2
#y=(2-(beta*x)+z)/2
#z=(1+x-y)/alfa
alfa = 4 #el valor NO puede ser 0 
beta = 0
A = np.array([[2, 0, -1], 
              [beta, 2, -1], 
              [-1, 1, alfa]])
a = np.array([1, 2, 1])

D = np.diag(np.diag(A))
LU = A - D
#Matriz T
T = np.dot(np.linalg.inv(D), -LU)
vals = np.linalg.eig(T)
valProps = vals[0]
#Se verifica si el método converge por el teorema de convergencia
for v in valProps:
    if abs(v) >= 1:
        print("La solucion no converge")
        break
x0 = np.zeros(3)
tol=1e-10
x, i, iters, sols = jacobi(A, a, tol, 50, x0)
y, iteraciones = gaussSeidel(A, a, tol, 50, x0)
print("usar de base x0 = [0,0,0]")
print("Solucion con Jacobi: ", x)
print("Iteraciones: ", i-1)
print("Solucion con Gauss-Seidel: ", y)
print("Iteraciones: ", iteraciones)
print("Solucion con numpy: ", np.linalg.solve(A, a))#confirmacion con numpy
x0 = np.array([1, 2, 3])
x, i, iters, sols = jacobi(A, a, tol, 11, x0)#para la tabla de exactamente 10 iteraciones
print()
print("Tabla metodo Jacobi con x0 = [1, 2, 3]:")
print("Solucion con Jacobi",x)
print("Iteraciones: ",i-1)
df = pd.DataFrame()
df["Iteracion"] = iters
df["Vector x"] = sols
print(df)